### ISSUE TITLE
Problems with dependency to piper-library-os

### ISSUE THREAD

**Issue by koenix** [SAP/cloud-s4-sdk-pipeline-lib#12]
Hi!

We are using the cloud-s4-sdk-pipeline-lib project to create an own build pipeline. This pipeline is very simple and basically runs End-2-End / synthetic monitoring tests over our suite of Microservices (each of them uses the standard cloud-s4-sdk-pipeline). 

Until last week, our Jenkinsfile included `@Library(['piper-library-os'])` and everything worked fine. Then we suddenly had issues with our pipeline and figured out, that we needed to specify an absolute piper-library-os version (we looked that up in the cloud-s4-sdk-pipeline). So we updated our Jenkinsfile and replaced the piper-library-os statement with `@Library(['piper-library-os@6dc13801b0223b9d4ea93eb36098773edf504883'])`, added the step `library "piper-library-os@6dc13801b0223b9d4ea93eb36098773edf504883"` and again, everything was fine. 

This week, the pipeline crashed again: `npm install` failed from the script `stageBuildFrontend`. After some research we found out, that the piper-library-os version used in the cloud-s4-sdk-pipeline changed to `@Library(['piper-library-os@2716054392ead88ecba5c984967d1ab64279db02'])`. After switching to that version, our build pipeline was running fine again.

Is there a way to avoid the need, to specify the version of `piper-library-os`? It's quite time consuming to identify the issue and to fix the build pipelines.

Thanks and kind regards,
Helmut

**Comment by daniel-kurzynski** [comment]
Hello Helmut,
As discussed:
Instead of `@Library(['piper-library-os'])` and `library "piper-library-os@...` you can use the step [loadPiper](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/master/vars/loadPiper.groovy).

However, better is even to use the step [initS4SdkPipelineLibrary](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/master/vars/initS4SdkPipelineLibrary.groovy).

You can find an example here:
https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/s4sdk-pipeline.groovy#L17

To get the configuration for a stage you can use:
`script?.commonPipelineEnvironment?.configuration?.stages?.<REPLACE WITH STAGENAME>`

Kind regards,
Daniel

**Comment by koenix** [comment]
Hi Daniel,

thanks again for your support, the issue is now resolved. The pipeline now completes successfully without the direct piper dependency.

Kind regards,
Helmut
